import { useSession } from "next-auth/react";
import Head from "next/head";
import React, { useState, useEffect } from "react";
import { useContext } from "react";
import { ToastContainer } from "react-toastify";
import "react-toastify/dist/ReactToastify.css";
import { Store } from "../utils/Store";
import Navbar from "./Navbar";

export default function Layout({ children, title }) {
  const [cartItems, setCartItems] = useState();

  const { status, data: session } = useSession();
  const { state } = useContext(Store);
  const { cart } = state;

  useEffect(() => {
    setCartItems(cart.cartItems.reduce((a, b) => a + b.quantity, 0));
  }, [cart.cartItems]);

  return (
    <>
      <div>
        <Head>
          <title>{title ? title + " - Fruits" : "Fruits"}</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>

        <ToastContainer position="bottom-center" limit={1} />

        <div className="flex min-h-screen flex-col justify-between bg-[#fafafa]">
          <Navbar cartItems={cartItems} session={session} status={status} />
          <main className="container m-auto mt-4 px-4 md:max-w-[900px]">
            {children}
          </main>
          <footer className="flex h-10 justify-center items-center shadow-inner">
            <p>Copyright © 2022 Fruits</p>
          </footer>
        </div>
      </div>
    </>
  );
}
